version: '3'
services:
  mysql:
      image: mysql:8.0
      container_name: mysql
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: micro  # Default database for test-service
      ports:
        - "3307:3306"
      volumes:
        - ./mysql_data:/var/lib/mysql
