spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          predicates:
            - Path=/api/user/**
          uri: lb://user-service
          filters:
            - JwtRequestFilter

        - id: hello-service
          predicates:
            - Path=/api/hello/**
          uri: lb://hello-service
          filters:
            - JwtRequestFilter

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
