server:
  port: 8085

spring:
  application:
    name: hello-service

eureka:
  client:
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
  instance:
    preferIpAddress: true
